"""Agrega created_at y updated_at a user

Revision ID: 840abb304f2b
Revises: ddeb658a80a0
Create Date: 2025-07-29 12:40:41.899722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840abb304f2b'
down_revision: Union[str, Sequence[str], None] = 'ddeb658a80a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
